export const TYPES = {
    Api: Symbol('Api'),
    Bot: Symbol('Bot'),
    Broadcast: Symbol('Broadcast'),
    BroadcastProvider: Symbol('BroadcastProvider'),
    Client: Symbol('Client'),
    CommandList: Symbol('CommandList'),
    MessageResponder: Symbol('MessageResponder'),

    Settings: Symbol('Settings'),
    SettingsDB: Symbol('SettingsDB'),
    ScheduleDB: Symbol('ScheduleDB'),
    PayoutDB: Symbol('PayoutDB'),
    RecruitDB: Symbol('RecruitDB'),
    ImageDB: Symbol('ImageDB'),
    Config: Symbol('Config'),
    Permissions: Symbol('Permissions'),

    // .env
    Token: Symbol('Token'),
    Prefix: Symbol('Prefix'),
    ApiClient: Symbol('ApiClient'),
    RedisClient: Symbol('RedisClient'),
    ApiHost: Symbol('ApiHost'),

    // Commands
    Eval: Symbol('Eval'),
    Ping: Symbol('Ping'),
    Stats: Symbol('Stats'),
    MyLevel: Symbol('MyLevel'),
    GuildConfiguration: Symbol('GuildConfiguration'),

    Pit: Symbol('Pit'),
    PitOpen: Symbol('PitOpen'),
    PitStarting: Symbol('PitStarting'),
    PitPost: Symbol('PitPost'),
    PitHolding: Symbol('PitHolding'),
    PitSetRole: Symbol('PitSetRole'),
    PitSetPostThreshold: Symbol('PitSetPostThreshold'),
    PitStatus: Symbol('PitStatus'),
    PitClose: Symbol('PitClose'),
    PitHelp: Symbol('PitHelp'),

    Schedule: Symbol('Schedule'),
    ScheduleAdd: Symbol('ScheduleAdd'),
    ScheduleList: Symbol('ScheduleList'),
    ScheduleRemove: Symbol('ScheduleRemove'),
    ScheduleExecute: Symbol('ScheduleExecute'),

    Compare: Symbol('Compare'),
    GCompare: Symbol('GCompare'),
    TWC: Symbol('TWC'),
    Profile: Symbol('Profile'),
    Faction: Symbol('Faction'),
    Mods: Symbol('Mods'),
    Unit: Symbol('Unit'),
    Team: Symbol('Team'),
    UnitSearch: Symbol('UnitSearch'),
    Poster: Symbol('Poster'),
    Payout: Symbol('Payout'),
    Whois: Symbol('Whois'),
    Register: Symbol('Register'),
    Recruiting: Symbol('Recruiting'),
    Image: Symbol('Image'),

    Help: Symbol('Help'),
};
